import os from "node:os";
import path from "node:path";
import fs from "fs-extra";
import { afterEach, describe, expect, it } from "vitest";
import { generateImagesCommand } from "../src/commands/generate-images.js";
import { initProject } from "../src/commands/init.js";
import { packageProjectCommand } from "../src/commands/pack.js";
import { prepareProjectCommand } from "../src/commands/prepare.js";
import { promptsProjectCommand } from "../src/commands/prompts.js";
import { remotionProjectCommand } from "../src/commands/remotion.js";

let cleanupPaths: string[] = [];

afterEach(async () => {
  await Promise.all(cleanupPaths.map((item) => fs.remove(item)));
  cleanupPaths = [];
});

describe("remotion output", () => {
  it("creates a standalone Remotion preview/render project", async () => {
    const root = await fs.mkdtemp(path.join(os.tmpdir(), "video-pack-remotion-"));
    cleanupPaths.push(root);
    const cwd = process.cwd();

    try {
      process.chdir(root);
      await initProject("sample");
      const projectPath = path.join(root, "sample");

      await prepareProjectCommand(projectPath, { force: true });
      await promptsProjectCommand(projectPath, { force: true });
      await generateImagesCommand(projectPath, { provider: "mock", force: true });

      const output = await remotionProjectCommand(projectPath, { force: true });
      const remotionRoot = path.join(projectPath, "output", "08_remotion");

      expect(output).toContain("Remotion output complete");
      expect(await fs.pathExists(path.join(remotionRoot, "package.json"))).toBe(true);
      expect(await fs.pathExists(path.join(remotionRoot, "src", "Root.tsx"))).toBe(true);
      expect(await fs.pathExists(path.join(remotionRoot, "src", "data", "project-data.json"))).toBe(true);
      expect(await fs.pathExists(path.join(remotionRoot, "public", "assets", "images"))).toBe(true);

      const packageJson = await fs.readJson(path.join(remotionRoot, "package.json"));
      expect(packageJson.scripts.render).toContain("remotion render");

      const data = await fs.readJson(path.join(remotionRoot, "src", "data", "project-data.json"));
      expect(data.scenes[0].image.src).toContain("assets/images/");
      expect(data.durationInFrames).toBeGreaterThan(0);
    } finally {
      process.chdir(cwd);
    }
  });

  it("is generated by package", async () => {
    const root = await fs.mkdtemp(path.join(os.tmpdir(), "video-pack-remotion-package-"));
    cleanupPaths.push(root);
    const cwd = process.cwd();

    try {
      process.chdir(root);
      await initProject("sample");
      const projectPath = path.join(root, "sample");

      await prepareProjectCommand(projectPath, { force: true });
      await promptsProjectCommand(projectPath, { force: true });
      await packageProjectCommand(projectPath, { force: true });

      const readme = await fs.readFile(path.join(projectPath, "output", "08_remotion", "README.md"), "utf8");
      expect(readme).toContain("Remotion Draft");
      expect(readme).toContain("npm run dev");
    } finally {
      process.chdir(cwd);
    }
  });
});
